// <auto-generated />
using System;
using ContactCenter.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ContactCenter.Data.Migrations
{
    [DbContext(typeof(EDRSMContext))]
    [Migration("20240906155104_IsAdmin-contactUser")]
    partial class IsAdmincontactUser
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ContactCenter.Data.Agent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Agent", (string)null);
                });

            modelBuilder.Entity("ContactCenter.Data.AgentSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CheckInTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("CheckoutTime")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "AgentId" }, "IX_AgentSession_AgentId");

                    b.ToTable("AgentSession", (string)null);
                });

            modelBuilder.Entity("ContactCenter.Data.Call", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<string>("CallerId")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContactId")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<int>("DirectionId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValueSql("''::character varying");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("NotesJson")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("TicketId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "AgentId" }, "IX_Call_AgentId");

                    b.HasIndex(new[] { "CategoryId" }, "IX_Call_CategoryId");

                    b.HasIndex(new[] { "ContactId" }, "IX_Call_ContactId");

                    b.HasIndex(new[] { "LocationId" }, "IX_Call_LocationId");

                    b.HasIndex(new[] { "TicketId" }, "IX_Call_TicketId");

                    b.ToTable("Call", (string)null);
                });

            modelBuilder.Entity("ContactCenter.Data.CallCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CreatorId" }, "IX_CallCategory_CreatorId");

                    b.HasIndex(new[] { "ParentId" }, "IX_CallCategory_ParentId");

                    b.ToTable("CallCategory", (string)null);
                });

            modelBuilder.Entity("ContactCenter.Data.Contact", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<Guid>("ContactUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContactUserId1")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("text");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("ContactUserId1");

                    b.HasIndex(new[] { "CreatorId" }, "IX_Contact_CreatorId");

                    b.HasIndex(new[] { "LocationId" }, "IX_Contact_LocationId");

                    b.ToTable("Contact", (string)null);
                });

            modelBuilder.Entity("ContactCenter.Data.Councillor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CloudinaryPublicId")
                        .HasColumnType("text");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Ward")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("Councillor", (string)null);
                });

            modelBuilder.Entity("ContactCenter.Data.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("character varying");

                    b.Property<string>("DialingCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.ToTable("Country", (string)null);
                });

            modelBuilder.Entity("ContactCenter.Data.EmailConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<bool>("EnableSsl")
                        .HasColumnType("boolean");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.Property<string>("SenderDisplayName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("TargetId")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CreatorId" }, "IX_EmailConfig_CreatorId");

                    b.ToTable("EmailConfig", (string)null);
                });

            modelBuilder.Entity("ContactCenter.Data.Entities.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Container")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Size")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UniqueId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Attachment", (string)null);
                });

            modelBuilder.Entity("ContactCenter.Data.Entities.FaqCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("FaqCategories");
                });

            modelBuilder.Entity("ContactCenter.Data.Entities.UserExternalLogin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AuthSchemeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LoginId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("PictureUrl")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserExternalLogins");
                });

            modelBuilder.Entity("ContactCenter.Data.Faq", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ByCategorySorter")
                        .HasColumnType("integer");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("FaqCategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FaqCategoryId");

                    b.ToTable("Faq", (string)null);
                });

            modelBuilder.Entity("ContactCenter.Data.Identity.ContactUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<bool>("AgreedToTerms")
                        .HasColumnType("boolean");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("text");

                    b.Property<int>("CountryOfOriginId")
                        .HasColumnType("integer");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("IdentificationNumber")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<int>("IdentificationTypeId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MunicipalityAccountNumber")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<int>("PreferredContactMethodId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ProfilePictureId")
                        .HasColumnType("uuid");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.Property<int>("Ward")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("Citizen_pkey");

                    b.HasIndex("CountryOfOriginId");

                    b.HasIndex("ProfilePictureId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("ContactUser", (string)null);
                });

            modelBuilder.Entity("ContactCenter.Data.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("GeoLatitude")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("GeoLongitude")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CreatorId" }, "IX_Location_CreatorId");

                    b.HasIndex(new[] { "ParentId" }, "IX_Location_ParentId");

                    b.ToTable("Location", (string)null);
                });

            modelBuilder.Entity("ContactCenter.Data.Query", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdminId")
                        .HasColumnType("uuid")
                        .HasColumnName("AdminID");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("QueryText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("Status ");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("UserID");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "AdminId" }, "IX_Queries_AdminID");

                    b.ToTable("Queries");
                });

            modelBuilder.Entity("ContactCenter.Data.RequestedPaymentPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdminReviewerId")
                        .HasColumnType("text");

                    b.Property<string>("AdminReviewerName")
                        .HasColumnType("text");

                    b.Property<string>("AdminReviewerSurname")
                        .HasColumnType("text");

                    b.Property<bool>("AgreeToTermsAndConditions")
                        .HasColumnType("boolean");

                    b.Property<decimal>("AmountDue")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("AmountPaidDown")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("ApplicationReference")
                        .HasColumnType("text");

                    b.Property<string>("CellphoneNumber")
                        .HasColumnType("text");

                    b.Property<decimal>("DepositPercentage")
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("ImpliedMonthlyPayment")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("MunicipalityAccountNumber")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("PaymentPlan")
                        .HasColumnType("text");

                    b.Property<string>("ReasonForPlan")
                        .HasColumnType("text");

                    b.Property<DateTime>("RequestPostedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("RequestReviewedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ReviewComment")
                        .HasColumnType("text");

                    b.Property<string>("ReviewStatus")
                        .HasColumnType("text");

                    b.Property<string>("SelectedAccount")
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RequestedPaymentPlans", (string)null);
                });

            modelBuilder.Entity("ContactCenter.Data.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssigneeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AssignmentDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContactId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatorId")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("LocationAddress")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("NotesJson")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("ResolutionDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.Property<int?>("TicketHeadingId")
                        .HasColumnType("integer");

                    b.Property<int?>("TicketStatusId")
                        .HasColumnType("integer");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("AssigneeId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ContactId");

                    b.HasIndex("CreatorId");

                    b.HasIndex("LocationId");

                    b.HasIndex("TicketHeadingId");

                    b.HasIndex("TicketStatusId");

                    b.ToTable("Ticket", (string)null);
                });

            modelBuilder.Entity("ContactCenter.Data.TicketAudit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DetailedDescription")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("NameOfUpdater")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ShortSummary")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("StatusChangeTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.Property<string>("StatusName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SurnameOfUpdater")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "StatusId" }, "IX_TicketAudit_StatusId");

                    b.HasIndex(new[] { "TicketId" }, "IX_TicketAudit_TicketId");

                    b.ToTable("TicketAudit", (string)null);
                });

            modelBuilder.Entity("ContactCenter.Data.TicketCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CreatorId" }, "IX_TicketCategory_CreatorId");

                    b.HasIndex(new[] { "ParentId" }, "IX_TicketCategory_ParentId");

                    b.ToTable("TicketCategory", (string)null);
                });

            modelBuilder.Entity("ContactCenter.Data.TicketHeading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("HeadingName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("TicketTypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "TicketTypeId" }, "IX_TicketHeading_TicketTypeId");

                    b.ToTable("TicketHeading", (string)null);
                });

            modelBuilder.Entity("ContactCenter.Data.TicketStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.ToTable("TicketStatus", (string)null);
                });

            modelBuilder.Entity("ContactCenter.Data.TicketType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.ToTable("TicketType", (string)null);
                });

            modelBuilder.Entity("ContactCenter.Data.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ActivationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("AuthRecoveryCodes")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("AuthenticatorKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("LockoutExpiryDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LoginId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Mobile")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<string>("SecurityStamp")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("TwoFactorAuthEnabled")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CreatorId" }, "IX_User_CreatorId");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("ContactCenter.Data.UserSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("AuthSchemeId")
                        .HasColumnType("integer");

                    b.Property<string>("ClientIpAddress")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("LoginDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("LogoutDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId" }, "IX_UserSession_UserId");

                    b.ToTable("UserSession", (string)null);
                });

            modelBuilder.Entity("ContactCenter.Data.Agent", b =>
                {
                    b.HasOne("ContactCenter.Data.User", "Creator")
                        .WithOne("Agent")
                        .HasForeignKey("ContactCenter.Data.Agent", "Id")
                        .IsRequired()
                        .HasConstraintName("Agent_Id_fkey");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("ContactCenter.Data.AgentSession", b =>
                {
                    b.HasOne("ContactCenter.Data.Agent", "Agent")
                        .WithMany("AgentSessions")
                        .HasForeignKey("AgentId")
                        .IsRequired()
                        .HasConstraintName("AgentSession_AgentId_fkey");

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("ContactCenter.Data.Call", b =>
                {
                    b.HasOne("ContactCenter.Data.Agent", "Agent")
                        .WithMany("Calls")
                        .HasForeignKey("AgentId")
                        .IsRequired()
                        .HasConstraintName("Call_AgentId_fkey");

                    b.HasOne("ContactCenter.Data.CallCategory", "Category")
                        .WithMany("Calls")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("Call_CategoryId_fkey");

                    b.HasOne("ContactCenter.Data.Contact", "Contact")
                        .WithMany("Calls")
                        .HasForeignKey("ContactId")
                        .HasConstraintName("Call_ContactId_fkey");

                    b.HasOne("ContactCenter.Data.Location", "Location")
                        .WithMany("Calls")
                        .HasForeignKey("LocationId")
                        .HasConstraintName("Call_LocationId_fkey");

                    b.HasOne("ContactCenter.Data.Ticket", "Ticket")
                        .WithMany("Calls")
                        .HasForeignKey("TicketId")
                        .HasConstraintName("Call_ConversationId_fkey");

                    b.Navigation("Agent");

                    b.Navigation("Category");

                    b.Navigation("Contact");

                    b.Navigation("Location");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("ContactCenter.Data.CallCategory", b =>
                {
                    b.HasOne("ContactCenter.Data.User", "Creator")
                        .WithMany("CallCategories")
                        .HasForeignKey("CreatorId")
                        .IsRequired()
                        .HasConstraintName("CallCategory_CreatorId_fkey");

                    b.HasOne("ContactCenter.Data.CallCategory", "Parent")
                        .WithMany("InverseParent")
                        .HasForeignKey("ParentId")
                        .HasConstraintName("CallCategory_ParentId_fkey");

                    b.Navigation("Creator");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("ContactCenter.Data.Contact", b =>
                {
                    b.HasOne("ContactCenter.Data.Identity.ContactUser", "ContactUser")
                        .WithMany("Contacts")
                        .HasForeignKey("ContactUserId1");

                    b.HasOne("ContactCenter.Data.User", "Creator")
                        .WithMany("Contacts")
                        .HasForeignKey("CreatorId")
                        .IsRequired()
                        .HasConstraintName("Contact_CreatorId_fkey");

                    b.HasOne("ContactCenter.Data.Location", "Location")
                        .WithMany("Contacts")
                        .HasForeignKey("LocationId")
                        .HasConstraintName("Contact_LocationId_fkey");

                    b.Navigation("ContactUser");

                    b.Navigation("Creator");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("ContactCenter.Data.EmailConfig", b =>
                {
                    b.HasOne("ContactCenter.Data.User", "Creator")
                        .WithMany("EmailConfigs")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_EmailConfig_User");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("ContactCenter.Data.Entities.FaqCategory", b =>
                {
                    b.HasOne("ContactCenter.Data.Entities.FaqCategory", "Parent")
                        .WithMany("InverseParent")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("ContactCenter.Data.Entities.UserExternalLogin", b =>
                {
                    b.HasOne("ContactCenter.Data.User", "User")
                        .WithMany("UserExternalLogins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ContactCenter.Data.Faq", b =>
                {
                    b.HasOne("ContactCenter.Data.Entities.FaqCategory", null)
                        .WithMany("Faqs")
                        .HasForeignKey("FaqCategoryId");
                });

            modelBuilder.Entity("ContactCenter.Data.Identity.ContactUser", b =>
                {
                    b.HasOne("ContactCenter.Data.Country", "CountryOfOrigin")
                        .WithMany("ContactUsers")
                        .HasForeignKey("CountryOfOriginId")
                        .IsRequired()
                        .HasConstraintName("Citizen_CountryOfOriginId_fkey");

                    b.HasOne("ContactCenter.Data.Entities.Attachment", "ProfilePicture")
                        .WithMany("ContactUsers")
                        .HasForeignKey("ProfilePictureId")
                        .HasConstraintName("Citizen_ProfilePictureId_fkey");

                    b.HasOne("ContactCenter.Data.User", "User")
                        .WithOne("ContactUser")
                        .HasForeignKey("ContactCenter.Data.Identity.ContactUser", "UserId")
                        .HasConstraintName("Citizen_UserId_fkey");

                    b.Navigation("CountryOfOrigin");

                    b.Navigation("ProfilePicture");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ContactCenter.Data.Location", b =>
                {
                    b.HasOne("ContactCenter.Data.User", "Creator")
                        .WithMany("Locations")
                        .HasForeignKey("CreatorId")
                        .IsRequired()
                        .HasConstraintName("Location_CreatorId_fkey");

                    b.HasOne("ContactCenter.Data.Location", "Parent")
                        .WithMany("InverseParent")
                        .HasForeignKey("ParentId")
                        .HasConstraintName("Location_ParentId_fkey");

                    b.Navigation("Creator");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("ContactCenter.Data.Ticket", b =>
                {
                    b.HasOne("ContactCenter.Data.Agent", null)
                        .WithMany("Tickets")
                        .HasForeignKey("AgentId");

                    b.HasOne("ContactCenter.Data.User", "Assignee")
                        .WithMany("Tickets")
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ContactCenter.Data.TicketCategory", "Category")
                        .WithMany("Tickets")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ContactCenter.Data.Contact", "Contact")
                        .WithMany("Tickets")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ContactCenter.Data.Identity.ContactUser", "Creator")
                        .WithMany("Tickets")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ContactCenter.Data.Location", "Location")
                        .WithMany("Tickets")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ContactCenter.Data.TicketHeading", null)
                        .WithMany("Incidents")
                        .HasForeignKey("TicketHeadingId");

                    b.HasOne("ContactCenter.Data.TicketStatus", "TicketStatus")
                        .WithMany("Tickets")
                        .HasForeignKey("TicketStatusId");

                    b.Navigation("Assignee");

                    b.Navigation("Category");

                    b.Navigation("Contact");

                    b.Navigation("Creator");

                    b.Navigation("Location");

                    b.Navigation("TicketStatus");
                });

            modelBuilder.Entity("ContactCenter.Data.TicketAudit", b =>
                {
                    b.HasOne("ContactCenter.Data.TicketStatus", "Status")
                        .WithMany("TicketAudits")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("TicketAudit_StatusId_fkey");

                    b.HasOne("ContactCenter.Data.Ticket", "Ticket")
                        .WithMany("TicketAudits")
                        .HasForeignKey("TicketId")
                        .IsRequired()
                        .HasConstraintName("TicketAudit_TicketId_fkey");

                    b.Navigation("Status");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("ContactCenter.Data.TicketCategory", b =>
                {
                    b.HasOne("ContactCenter.Data.User", "Creator")
                        .WithMany("TicketCategories")
                        .HasForeignKey("CreatorId")
                        .IsRequired()
                        .HasConstraintName("TicketCategory_CreatorId_fkey");

                    b.HasOne("ContactCenter.Data.TicketCategory", "Parent")
                        .WithMany("InverseParent")
                        .HasForeignKey("ParentId")
                        .HasConstraintName("TicketCategory_ParentId_fkey");

                    b.Navigation("Creator");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("ContactCenter.Data.TicketHeading", b =>
                {
                    b.HasOne("ContactCenter.Data.TicketType", "TicketType")
                        .WithMany("TicketHeadings")
                        .HasForeignKey("TicketTypeId")
                        .IsRequired()
                        .HasConstraintName("TicketHeading_TicketTypeId_fkey");

                    b.Navigation("TicketType");
                });

            modelBuilder.Entity("ContactCenter.Data.User", b =>
                {
                    b.HasOne("ContactCenter.Data.User", "Creator")
                        .WithMany("InverseCreator")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("User_CreatorId_fkey");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("ContactCenter.Data.UserSession", b =>
                {
                    b.HasOne("ContactCenter.Data.User", "User")
                        .WithMany("UserSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("UserSession_UserId_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ContactCenter.Data.Agent", b =>
                {
                    b.Navigation("AgentSessions");

                    b.Navigation("Calls");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("ContactCenter.Data.CallCategory", b =>
                {
                    b.Navigation("Calls");

                    b.Navigation("InverseParent");
                });

            modelBuilder.Entity("ContactCenter.Data.Contact", b =>
                {
                    b.Navigation("Calls");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("ContactCenter.Data.Country", b =>
                {
                    b.Navigation("ContactUsers");
                });

            modelBuilder.Entity("ContactCenter.Data.Entities.Attachment", b =>
                {
                    b.Navigation("ContactUsers");
                });

            modelBuilder.Entity("ContactCenter.Data.Entities.FaqCategory", b =>
                {
                    b.Navigation("Faqs");

                    b.Navigation("InverseParent");
                });

            modelBuilder.Entity("ContactCenter.Data.Identity.ContactUser", b =>
                {
                    b.Navigation("Contacts");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("ContactCenter.Data.Location", b =>
                {
                    b.Navigation("Calls");

                    b.Navigation("Contacts");

                    b.Navigation("InverseParent");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("ContactCenter.Data.Ticket", b =>
                {
                    b.Navigation("Calls");

                    b.Navigation("TicketAudits");
                });

            modelBuilder.Entity("ContactCenter.Data.TicketCategory", b =>
                {
                    b.Navigation("InverseParent");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("ContactCenter.Data.TicketHeading", b =>
                {
                    b.Navigation("Incidents");
                });

            modelBuilder.Entity("ContactCenter.Data.TicketStatus", b =>
                {
                    b.Navigation("TicketAudits");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("ContactCenter.Data.TicketType", b =>
                {
                    b.Navigation("TicketHeadings");
                });

            modelBuilder.Entity("ContactCenter.Data.User", b =>
                {
                    b.Navigation("Agent");

                    b.Navigation("CallCategories");

                    b.Navigation("ContactUser");

                    b.Navigation("Contacts");

                    b.Navigation("EmailConfigs");

                    b.Navigation("InverseCreator");

                    b.Navigation("Locations");

                    b.Navigation("TicketCategories");

                    b.Navigation("Tickets");

                    b.Navigation("UserExternalLogins");

                    b.Navigation("UserSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
